/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/pricingengines/loan/loanfunctions.hpp>
#include <ql/pricingengines/loan/discountingloanengine.hpp>

